AMREX_HOME ?= ../../amrex

PRECISION  = DOUBLE
PROFILE    = FALSE

DEBUG      = TRUE
DEBUG      = FALSE

#DIM        = 2
DIM       = 3

COMP	   = gnu

USE_MPI    = TRUE
USE_OMP    = FALSE 
USE_CUDA   = FALSE
USE_HYPRE  = TRUE

Bpack   := ./Make.package 
Blocs   := . 

HYPRE_DIR=../../hypre/src/hypre/

include ${ECHEM_DIR}/Make.echemAMR
